version = "1.0"

[main]
name = "SignaturePDF configuration"

    [main.digital_signature]
    name = "Set up digital signature"

        [main.digital_signature.warning]
        type = "alert"
        style = "info"
        ask.en = "Changing either the nickname will delete the current certificate and generate a new one"
        ask.fr = "Changer le surnom supprimera le certificat actuel et en génèrera un nouveau"

        [main.digital_signature.nss3_nick]
        ask.en = "Choose a nickname for the digital signature"
        ask.fr = "Choisissez un surnom pour la signature numérique"
        type = "string"
        pattern.regexp = '^[^\.]+$'
        pattern.error = "The nickname cannot contain a dot"
        bind = ":__INSTALL_DIR__/config/config.ini"
