packaging_format = 2

id = "signaturepdf"
name = "Signaturepdf"
description.en = "Sign (alone or with others), stamp, reorganize, edit metadata and compress PDF files"
description.fr = "Signez (seul ou à plusieurs), tamponnez, réorganisez, éditez les métadatas et compresser des fichiers PDF"

version = "1.7.0~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://pdf.24eme.fr/signature"
demo = "https://pdf.24eme.fr"
code = "https://github.com/24eme/signaturepdf"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/24eme/signaturepdf/archive/refs/tags/v1.7.0.tar.gz"
        sha256 = "480e16163cda2b479a7fabfaf9dd6a6d7fe2ba762f82b27ca140725d658a848a"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages ="php8.2-fpm, librsvg2-bin, pdftk, imagemagick, potrace"
