#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "signaturepdf"
name = "Signaturepdf"
description.en = "Sign (alone or with others), stamp, reorganize, edit metadata and compress PDF files"
description.fr = "Signez (seul ou à plusieurs), tamponnez, réorganisez, éditez les métadatas et compresser des fichiers PDF"

version = "1.8.0~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://pdf.24eme.fr/signature"
demo = "https://pdf.24eme.fr"
code = "https://github.com/24eme/signaturepdf"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.nss3_nick]
    type = "string"
    ask.en = "Choose a nickname for the digital signature"
    ask.fr = "Choisissez un surnom pour la signature numérique"
    pattern.regexp = '[^\.]+'
    pattern.error = "The nickname cannot contain a dot"
    default = "SignaturePDF"

[resources]
    [resources.sources.main]
    url = "https://github.com/24eme/signaturepdf/archive/refs/tags/v1.8.0.tar.gz"
    sha256 = "367a1518a7fa8af232ca4a5aab93e6584ad82a9356cd5029518e52b533307042"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    subdirs = ["nss"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.3-fpm, librsvg2-bin, pdftk, imagemagick, potrace, poppler-utils, libnss3-tools"
