test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.3e633d6c482fb61e0f96e1dbffccfd12a0d84886.name = "Upgrade from 1.1.1"






