#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

nss3_password=$(ynh_string_random)
ynh_app_setting_set --app=$app --key=nss3_password --value=$nss3_password

ynh_app_setting_set --key=php_upload_max_filesize --value=256M

ynh_app_setting_set --key=php_upload_max_filesize --value=256M
ynh_app_setting_set --key=php_memory_limit --value=256M
ynh_app_setting_set --key=php_post_max_filesize --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.ini" --destination="$install_dir/config/config.ini"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
