#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..."

if ynh_compare_current_package_version --comparison lt --version 1.7.0~ynh2
then
    nss3_nick="SignaturePDF"
    ynh_app_setting_set --app=$app --key=nss3_nick --value=$nss3_nick
    nss3_password=$(ynh_string_random)
    ynh_app_setting_set --app=$app --key=nss3_password --value=$nss3_password

    echo "# Digital signature configuration
NSS3_DIRECTORY=$data_dir/nss/
NSS3_PASSWORD=$nss3_password
NSS3_NICK=$nss3_nick
" >> $install_dir/config/config.ini
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --keep="config/config.ini"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
